---
- name: Terraform setup
  hosts: all
  become: true
  tasks:
    - name: Dependencies install
      apt:
        name:
          - gnupg
          - software-properties-common
          - curl
        state: present
        update_cache: yes

    - name: Keyring creation
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Check GPG
      stat:
        path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      register: hashicorp_key

    - name: Download GPG
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /tmp/hashicorp.gpg
        mode: '0644'
        timeout: 20
      when: not hashicorp_key.stat.exists

    - name: Dearmor GPG
      command: >
        gpg --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      when: not hashicorp_key.stat.exists

    - name: Add repo
      deb822_repository:
        name: hashicorp
        types: [deb]
        uris: https://apt.releases.hashicorp.com
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: [main]
        signed_by: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present

    - name: Update cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Terraform install
      apt:
        name: terraform
        state: present